# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy all project files
COPY . .

# Install system dependencies if needed
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Install uv and project dependencies
RUN pip install --no-cache-dir uv && \
    pip install --no-cache-dir .

EXPOSE 8000

# Run the server using main.py instead of module execution
CMD ["python", "main.py"]
